name = "ODBC"
uuid = "be6f12e9-ca4f-5eb2-a339-a4f995cc0291"
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
iODBC_debug_jll = "f7d3fe37-dbaf-5e02-82a8-8fd103cbf401"
unixODBC_jll = "1841a5aa-d9e2-579c-8226-32ed2af93ab1"

[compat]
DBInterface = "2"
DecFP = "0.4"
Tables = "1"
iODBC_debug_jll = "3.52"
unixODBC_jll = "2.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
